language: cpp
sudo: required

addons:
    apt:
        packages:
            - libcppunit-dev

install:
    - wget https://www.auto.tuwien.ac.at/~mkoegler/debian/pool/main/p/pthsem/pthsem_2.0.8.tar.gz
    - tar -zxf pthsem_2.0.8.tar.gz
    - cd pthsem-2.0.8
    - ./configure && make && sudo make install
    - cd ..

script:
    - export TZ=CET
    - export LD_LIBRARY_PATH=/usr/local/lib
    - autoreconf --install
    - ./configure --without-pth-test
    - make && make check && sudo make install
